### ISSUE TITLE
Bug: `FileSystemAdapter.getFilePath` return type is incorrect

### ISSUE THREAD

**Issue by mnaoumov** [obsidianmd/obsidian-api#148] opened 2023-12-23 17:57 UTC
According to the documentation 

```ts
getFilePath(normalizedPath: string): string;
```

but if you execute in the console

```js
app.vault.adapter.getFilePath('Note.md') instanceof String
false

app.vault.adapter.getFilePath('Note.md') instanceof app.vault.adapter.url.URL
true
```

**Comment by lishid** [comment] 2023-12-23 18:24
Ah that was a mistake in the implementation. Will be fixed in code in the next release, thanks.

**Closed by lishid** 2023-12-23 18:24 UTC

**Comment by mnaoumov** [comment] 2024-01-02 06:35
@lishid I would like to bring your attention to the fact that you closed this issue on Dec 23 saying that this is going to be fixed in the next release.

Then on Dec 26 you released Obsidian 1.5.3 which still contains the issue

**Comment by lishid** [comment] 2024-01-02 13:23
I can't reproduce. It gives me a string in 1.5.3.

**Comment by mnaoumov** [comment] 2024-01-03 00:28
Yes, I was wrong that's because I checked incorrectly

```js
app.vault.adapter.getFilePath('Note.md') instanceof String
false

typeof app.vault.adapter.getFilePath('Note.md') === 'string'
true
```
